# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site settings

#relative_permalinks: false


title: Tophat
email: au.vecchio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
include: ['_pages']
# Build settings
url: "http://avecchio.github.io"
markdown: kramdown
#theme: minima
social:
  asset_pipeline: /assets/images/social
  facebook:
    link: https://www.facebook.com/sparky912/
    logo: /facebook/facebook-128.png
  twitter:
    link: https://twitter.com/au_vecchio
    logo: /twitter/twitter-128.png
  googleplus:
    link: https://plus.google.com/u/0/104195218114901499296/posts
    logo: /googleplus/googleplus-128.png
  linkedin:
    link: https://www.linkedin.com/in/austin-vecchio-597000112
    logo: /linkedin/linkedin-128.png
  youtube:
    link: https://www.youtube.com/channel/UCzTmxNT1JqHhdB6Ofdbalpw
    logo: /youtube/youtube-128.png
  flickr:
    link: ''
    logo: /flickr/flickr-128.png
  spotify:
    link: http://open.spotify.com/user/professor-tophat
    logo: /spotify/spotify-128.png
  deviantart:
    link: ''
    logo: /deviantart/deviantart-128.png
  steam:
    link: http://steamcommunity.com/profiles/76561198303112111/
    logo: /steam/steam-128.png
  xbox:
    link: ''
    logo: /xbox/xbox-128.png
  twitch:
    link: http://www.twitch.tv/sparkysglitch/profile
    logo: /twitch/twitch-128.png
  goodreads:
    link: ''
    logo: /goodreads/goodreads-128.png
  hackernews:
    link: https://news.ycombinator.com/user?id=sparkysglitch
    logo: /hackernews/hackernews-128.png
  reddit:
    link: https://www.reddit.com/user/sparkysglitch/
    logo: /reddit/reddit-128.png
  kickstarter:
    link: https://www.kickstarter.com/profile/1809202118
    logo: /kickstarter/kickstarter-128.png
  stackoverflow:
    link: http://stackoverflow.com/users/3310597/user3310597
    logo: /stackoverflow/stackoverflow-128.png
